version: "3.7"

services:
  react-production:
    container_name: react-production
    restart: unless-stopped
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
